apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learning-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mahirberkano/learning-app-gitops.git
    targetRevision: main
    path: charts/learning-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: learning-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
